version : '3.5'

services:
  nginx:
      image : nginx_image
      depends_on:
        - wordpress
      container_name : nginx
      build :
        context: ./requirements/nginx
        # dockerfile: dockerfile.nginx
      ports:
        - "443:443"
      networks:
        - second_kick
      volumes:
        - wordpress:/var/www/html
  wordpress:
      image : wordpress_image
      container_name : wordpress
      depends_on:
        - mariadb
      networks:
        - second_kick
      build :
        context: ./requirements/wordpress
        # dockerfile: dockerfile.wordpress
      env_file: .env
      volumes:
        - wordpress:/var/www/html
  mariadb:
      image : mariadb_image
      container_name : mariadb
      networks:
        - second_kick
      build :
        context: ./requirements/mariadb
        # dockerfile: dockerfile.mariadb
      env_file: .env
      volumes:
        - mariadb:/var/lib/mysql
networks:
    second_kick:
      name: second_kick

volumes:
    wordpress:
      name: wordpress
#       driver: local
#       driver_opts:
#         device: /home/mnaqqad/data/wordpress
#         o: bind
#         type: none
    mariadb:
      name: mariadb
#       driver: local
#       driver_opts:
#         device: /home/mnaqqad/data/mariadb
#         o: bind
#         type: none
  

