version : '3.5'

services:
  nginx:
      image : nginx
      depends_on:
        - wordpress
      container_name : nginx_cont
      build :
        context: ./requirements/nginx
      ports:
        - "443:443"
      networks:
        - second_kick
      volumes:
        - wordpress:/var/www/html
      restart : always
  wordpress:
      image : wordpress
      container_name : wordpress_cont
      depends_on:
        - mariadb
      networks:
        - second_kick
      build :
        context: ./requirements/wordpress
      env_file: .env
      volumes:
        - wordpress:/var/www/html
      restart : always
  mariadb:
      image : mariadb
      container_name : mariadb_cont
      networks:
        - second_kick
      build :
        context: ./requirements/mariadb
      env_file: .env
      volumes:
        - mariadb:/var/lib/mysql
      restart : always
networks:
    second_kick:
      name: second_kick

volumes:
    wordpress:
      name: wordpress
      driver: local
      driver_opts:
       o: bind
       type: none
       device: /home/mnaqqad/data/wordpress
  
    mariadb:
      name: mariadb
      driver: local
      driver_opts:
        device: /home/mnaqqad/data/mariadb
        o: bind
        type: none
  

