FROM debian:buster

RUN apt -y update && apt -y upgrade && apt -y install curl \
&& apt install -y mariadb-server

COPY /conf/50-server.cnf /etc/mysql/mariadb.conf.d/50-server.cnf

COPY /tools/script_mariadb.sh /script_mariadb.sh

RUN chmod +x /script_mariadb.sh

CMD ["/script_mariadb.sh"]